# Generated by Django 4.0.1 on 2022-02-04 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('background_picture', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/')),
                ('friends', models.ManyToManyField(to='account.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='account.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_me', to='account.account')),
            ],
        ),
    ]
