# Generated by Django 4.0.1 on 2022-02-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending_friends',
            field=models.ManyToManyField(related_name='friend_requests', to='backend.Account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='backend.account'),
        ),
    ]
