# Generated by Django 4.0.1 on 2022-02-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_account_pending_friends_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pending_friends',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='backend.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.account')),
            ],
        ),
    ]
