# Generated by Django 4.0.5 on 2022-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechat',
            name='chat_privatechat_members_unique',
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(fields=('member_1', 'member_2'), name='chat_privatechat_members_are_unique'),
        ),
    ]
