# Generated by Django 4.0.5 on 2022-07-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
        ('account', '0001_initial'),
        ('chat', '0003_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='chat.groupchat')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_api.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='chat.groupchat'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
