# Generated by Django 4.0.5 on 2022-07-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('file_api', '0001_initial'),
        ('chat', '0004_groupmessage_alter_privatemessage_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_chat', to='file_api.image'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to='account.account'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupchat'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_messages', to='account.account'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.privatechat'),
        ),
    ]
