# Generated by Django 4.0.5 on 2022-07-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0002_alter_image_source'),
        ('chat', '0007_alter_chat_background_image_alter_chat_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='background_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_chat', to='file_api.image'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='file_api.image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_api.image'),
        ),
    ]
