# Generated by Django 4.0.5 on 2022-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/'),
        ),
    ]
